name: tiktok_clone_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  flutter_custom_tab_bar: ^1.2.1
  contained_tab_bar_view: ^0.8.0
  bottom_bar_matu: ^1.3.0
  dropdown_button2: ^2.0.0
  image_picker: ^0.8.7+1
  rotated_corner_decoration: ^2.1.0+1
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.1.1
  wave_transition: ^0.0.6
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ic_instagram.png
    - assets/ic_cek_semua.png
    - assets/ic_like.png
    - assets/ic_nav_akun_saya.png
    - assets/ic_video_saya.png
    - assets/ic_nav_home.png
    - assets/ic_nav_search.png
    - assets/ic_nav_tambah.png
    - assets/ic_nav_inbox.png
    - assets/ic_total_play.png
    - assets/image_video.png
    - assets/ic_music_vids.png
    - assets/ic_heart_vids.png
    - assets/ic_comment_vids.png
    - assets/ic_share_vids.png
    - assets/ic_disc_vids.png


